-- begin PIZZA_PIZZA
create unique index IDX_PIZZA_PIZZA_UK_NAME on PIZZA_PIZZA (NAME) where DELETE_TS is null ^
-- end PIZZA_PIZZA
-- begin PIZZA_PAYMENT
alter table PIZZA_PAYMENT add constraint FK_PIZZA_PAYMENT_ON_ORDER foreign key (ORDER_ID) references PIZZA_ORDER(ID)^
create index IDX_PIZZA_PAYMENT_ON_ORDER on PIZZA_PAYMENT (ORDER_ID)^
-- end PIZZA_PAYMENT
-- begin PIZZA_TOPPING
create unique index IDX_PIZZA_TOPPING_UK_NAME on PIZZA_TOPPING (NAME) where DELETE_TS is null ^
-- end PIZZA_TOPPING
-- begin PIZZA_INGRIDIENT
alter table PIZZA_INGRIDIENT add constraint FK_PIZZA_INGRIDIENT_ON_PIZZA foreign key (PIZZA_ID) references PIZZA_PIZZA(ID)^
alter table PIZZA_INGRIDIENT add constraint FK_PIZZA_INGRIDIENT_ON_TOPPING foreign key (TOPPING_ID) references PIZZA_TOPPING(ID)^
create index IDX_PIZZA_INGRIDIENT_ON_PIZZA on PIZZA_INGRIDIENT (PIZZA_ID)^
create index IDX_PIZZA_INGRIDIENT_ON_TOPPING on PIZZA_INGRIDIENT (TOPPING_ID)^
-- end PIZZA_INGRIDIENT
-- begin PIZZA_ORDER_ITEM
alter table PIZZA_ORDER_ITEM add constraint FK_PIZZA_ORDER_ITEM_ON_ORDER foreign key (ORDER_ID) references PIZZA_ORDER(ID)^
alter table PIZZA_ORDER_ITEM add constraint FK_PIZZA_ORDER_ITEM_ON_PIZZA foreign key (PIZZA_ID) references PIZZA_PIZZA(ID)^
create index IDX_PIZZA_ORDER_ITEM_ON_ORDER on PIZZA_ORDER_ITEM (ORDER_ID)^
create index IDX_PIZZA_ORDER_ITEM_ON_PIZZA on PIZZA_ORDER_ITEM (PIZZA_ID)^
-- end PIZZA_ORDER_ITEM
-- begin PIZZA_ORDER
alter table PIZZA_ORDER add constraint FK_PIZZA_ORDER_ON_DELIVER foreign key (DELIVER_ID) references PIZZA_ORDER(ID)^
create index IDX_PIZZA_ORDER_ON_DELIVER on PIZZA_ORDER (DELIVER_ID)^
-- end PIZZA_ORDER
